name: Docker Image CI

on:
  push:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set output variables
      id: vars
      run: |
        echo "NOWTIME=$(date +%s)" >> $GITHUB_OUTPUT

    # eg. for transform to lowercase, name of repo
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        flavor: latest=true
        tags: type=raw,value={{date 'YYYYMMDDhhmm' tz='Europe/Warsaw'}}

    - uses: docker/login-action@v3
      name: Log into registry ${{ env.REGISTRY }}
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}