name: Docker Image CI

on:
  push:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set output variables
      id: vars
      run: |
        echo "NOWTIME=$(date +%s)" >> $GITHUB_OUTPUT

    # eg. for transform to lowercase, name of repo
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        flavor: latest=true
        tags: type=raw,value={{date 'YYYYMMDDhhmm' tz='Europe/Warsaw'}}

    - uses: docker/login-action@v3
      name: Log into registry ${{ env.REGISTRY }}
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Retrieve the secret and add it to the ssh key
        env:
          MIKRUS_SSH: ${{ secrets.MIKRUS_SSH }}
        run: |
          mkdir -p ~/.ssh/
          chmod 700 ~/.ssh
          echo "$MIKRUS_SSH" > ~/.ssh/id_ed25519
          chmod 400 ~/.ssh/id_ed25519

      - name: Run command in Mikrus
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.MIKRUS_USER }}@${{ secrets.MIKRUS_HOST }} -p${{ secrets.MIKRUS_PORT }} "bash upgrade-docker.sh"